- name: Get SSH keys
  hosts: all
  gather_facts: no
  connection: local
  vars:
    - ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Change ssh port to 22
      set_fact:
        ansible_port: 22
    - name: Change ssh user to bocal
      set_fact:
        ansible_user: bocal
    - name: Copy SSH key
      command: "ssh-copy-id -i ~/.ssh/id_rsa.pub {{inventory_hostname}}"
      changed_when: false
    - name: Change desktop background of remote host
      script: osascript {{role_path}}/scripts/setbackground.applescript
